version: '3'

services:
  sorteo:
    build: sorteo
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sorteo_app:3306/staketickets?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always
    depends_on:
      sorteo_app:
        condition: service_healthy

  sorteo_app:
    image: mysql:8.0.33
    ports:
      - "3307:3306"  # Solo si querés acceder desde el host
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: staketickets
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
